name: habit_tracker
description: A responsive habit tracker with Firebase auth and CRUD.
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: 6.1.6
  provider: ^6.0.5
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  fluttertoast: ^9.0.0
  uuid: ^4.5.2
  flutter_form_builder: ^10.1.0
  flutter_animate: ^4.0.0
  shared_preferences: ^2.1.0
  form_builder_validators: ^11.2.0
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  share_plus: ^7.2.1

dependency_overrides:
  google_identity_services_web: ^0.3.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
